keys:
  - &hermes age13ltmy9wkmzfpw2qaak30xucq9d0hg7cklaq4pak287fup8z4xe2qvfrat8
  - &ouroboros age1q3y7cxkfw4t7ez2jmumh8ue8af0s7ttmvvph73zluazqvvdwx5lqr90hmy
creation_rules:
  - path_regex: secrets/user/shared.yaml$
    key_groups:
      - age:
        - *hermes
        - *ouroboros
  - path_regex: secrets/user/hermes.yaml$
    key_groups:
      - age:
        - *hermes
  - path_regex: secrets/user/ouroboros.yaml$
    key_groups:
      - age:
        - *ouroboros
  - path_regex: secrets/other/ouroboros.yaml$
    key_groups:
      - age:
        - *ouroboros
